name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # ផ្លាស់ប្តូរទៅ master ប្រសិនបើ Branch របស់អ្នកឈ្មោះ master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .Exercise
          branch: gh-branch 